### ISSUE TITLE
Console error message: 'Uncaught TypeError: Cannot read property 'id' of undefined'

### ISSUE THREAD

**Issue by rowild** [danwellman/to-do#4]
Further info from the console:

Uncaught TypeError: Cannot read property 'id' of undefined   -> list.js:51
ListViewModel.completeTask                                                   -> smokesignals.js:1
c.emit                                                                                        -> task.js:21 
TaskViewModel.toggleTaskComplete                                      -> knockout-3.2.0.js:79 (anonymous function)

This message pops up, when a task should be marked as completed. 

A console.log() only shows that the taskViewModel is undefined.
Here, a solution to the problem plus a little explanation would be great?!?! (I cannot solve this...) Thank you!

(Shouldn't there be an id be saved along with the task in the localStorage?)

**Comment by danwellman** [comment]
Again thanks for raising this issue. The problem here was that an instance of the task viewModel should be passed to the `emit` method as the second argument following the event name (`taskcompleted` in this case). When the instance is passed, the event handler, `completeTask` in this case, receives the instance as a parameter.

This was completely my fault and was missed from both the lesson as well as the source code here, making it very difficult for you to pin down. Sincere apologies.

This is now fixed and in master here. I'll add a comment to the lesson also explaining this. Thanks again for raising this.
